### ISSUE TITLE
Prices do not load anymore

### ISSUE THREAD

**Issue by dirkforke** [Deschain53/Sim_Company_Web_Calculator#2]
Hi! I tried with several browsers. The app does not load actual prices. Can you help. I love your tool and do know, that you do not use it anymore. Thanks

**Comment by dirkforke** [comment]
Great! Working again. Thanks

**Comment by Deschain53** [comment]
Hi. It has regular shut downs, but I think they are because of a free
service I use to get the prices from the game. They have limited request
per before the temporal pause of the service. Or it could be because of
GitHub.
I think I'll be able to give it proper maintaining in August, I have a ton
of things to do. However I appreciate the reports, it will help me to
identify the things to improve.
